spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            scope: name,email,profile_image
            authorization-grant-type: authorization_code
            client-secret: 3XzSL_5vFd
            client-id: bKXW9DdoeEGj8mxi1JgD
            client-name: Naver
          google:
            client-secret: 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
            client-id: 4209165689-i4a51mdk5h4jodsscdsac5l4knikup55.apps.googleusercontent.com
            scope: profile,email
        provider:
          naver:
            user-name-attribute: response
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            user-info-uri: https://openapi.naver.com/v1/nid/me
            token-uri: https://nid.naver.com/oauth2.0/token
